context:
  version: "0.13.1"

package:
  name: prisma-lint
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/prisma-lint/-/prisma-lint-${{ version }}.tgz
  sha256: adb5c2d00a7d5e466878359278f83ba70b1c61b2e80e42d6228d4af360340595

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - prisma-lint --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: A linter for Prisma schema files.
  homepage: https://github.com/loop-payments/prisma-lint
  repository: https://github.com/loop-payments/prisma-lint

extra:
  recipe-maintainers:
    - danielnachun
