context:
  version: "0.10.3"

package:
  name: prisma-lint
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/prisma-lint/-/prisma-lint-${{ version }}.tgz
  sha256: c803142ab93257e229535946770f08df4390b153714a0acaeefb4e92d5b1de49

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - prisma-lint --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: A linter for Prisma schema files.
  homepage: https://github.com/loop-payments/prisma-lint
  repository: https://github.com/loop-payments/prisma-lint

extra:
  recipe-maintainers:
    - danielnachun
